language: python
python: 2.7

os:
    - linux
    - osx

env:
    - TOX_ENV=py27
    - TOX_ENV=py34

install:
    - pip install tox coveralls

script:
    - tox --hashseed 0 -e $TOX_ENV

after_success:
    - coveralls
